ARG BASE
FROM ${BASE}

RUN apt-get update -qq \
 && apt-get install -y --no-install-recommends \
      python3 python3-venv python3-dev \
      ca-certificates make \
 && rm -rf /var/lib/apt/lists/*

RUN chmod -R a+w "${RUSTUP_HOME}" "${CARGO_HOME}"
